{% set name = "robotraconteur_companion_python" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robotraconteur/robotraconteur_companion_python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dbc24a48577419a7df723a1410888f212466df7987df0566b1c8bac5b311c76d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."

requirements:
  host:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - pip
    - general_robotics_toolbox >=0.7.1
    - numpy
  run:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - general_robotics_toolbox >=0.7.1
    - numpy

test:
  requires:
    - pytest
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - >- 
      pytest test/ --verbose --ignore test/util/test_local_identifier_manager.py 
      --ignore test/util/test_infofileloader.py --ignore test/util/test_infofileloader.py
      --ignore test/util/test_task_generator.py

about:
  home: http://robotraconteur.com
  summary: 'Companion library for the Robot Raconteur Python core library'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - traversaro
    - johnwason
